GET http://localhost:3001/api/sessions/current

###

POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "email": "gabriele.piazza@example.com",
    "password": "gabriele"
}

###

DELETE http://localhost:3001/api/sessions/current

###

GET http://localhost:3001/api/courses

###

GET http://localhost:3001/api/plan

###

PUT http://localhost:3001/api/plan
Content-Type: application/json

{
    "CourseCodes": ["02GOLOV", "02LSEOV", "01SQLOV"],
    "typeofPlan": "full-time"
}

###

POST http://localhost:3001/api/plan
Content-Type: application/json

{
    "typeofPlan": "full-time",
    "CourseCodes": ["02GOLOV", "02LSEOV", "01OTWOV"]
}

###

DELETE http://localhost:3001/api/plan

###